### ISSUE TITLE
ModuleNotFoundError: No module named 'o365spray'

### ISSUE THREAD

**Issue by smooreup** [0xZDH/o365spray#22]
o365spray --validate --domain test.com --proxy-url https://127.0.0.1:8080

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kali/Desktop/tools/o365spray/o365spray/__main__.py", line 11, in <module>
    from o365spray import __version__
ModuleNotFoundError: No module named 'o365spray'

Issue after running the installation in the following way

git clone https://github.com/0xZDH/o365spray.git
cd o365spray
pip install -r requirements.txt

**Comment by 0xZDH** [comment]
Can you provide some more information here -- what version of the tool are you attempting to run?

Looking at your command, you appear to be invoking o365spray as if you installed it as a local package vs. your install command only installing the dependencies. Testing locally I am unable to reproduce.

Side note: The `--proxy-url` flag is explicitly for FireProx API usage - based on your proxy value, you will likely want to use the `--proxy` flag instead.

**Comment by tijldeneut** [comment]
Hi, I encountered the same issue. It has to do with installing o365spray using the setup script (e.g. `python3 setup.py install`) to have the _o365spray_ command available everywhere. 
It would run only when started from main o365spray folder.
The issue seems to be fixed by adding  `__init__.py` files to each sub folder before installation, I've forked it and will perform a merge request, feel free to decline or ignore and implement other fixes as desired.

**Comment by charel420** [comment]
`pip3 install .`  fixes it for me
